### ISSUE TITLE
Temp in C instead of F

### ISSUE THREAD

**Issue by HA-Peet** [jdeath/BLE-YC01#5]
I would like the temperature in Celcius instead of Fahrenheit. In the code it's only Fahrenheit.
Please add the Celcius as well with the option uncomment the option needed.
Can't figure what 'message' it should be. Uncommenting the debug-line only gives me a [v]

**Comment by jdeath** [comment]
I think you can switch it in the Home Assistant UI. It is bad form to make two different temperature fields. If your system default unit is C, it should do it automatically. Or make a template sensor to do the conversion for you. Or edit the code and do the conversion yourself.
