### ISSUE TITLE
New update chlorine error?

### ISSUE THREAD

**Issue by pergolafabio** [jdeath/BLE-YC01#7]
Hi, I saw a new update today, but the Chlorine sensor doesnt work anymore?

```
2024-06-03 16:24:36.044 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.c0_00_00_01_a5_c4_free_chlorine for domain sensor with platform ble_yc01
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1359, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1009, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1015, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 676, in state
    raise ValueError(
ValueError: Sensor sensor.c0_00_00_01_a5_c4_free_chlorine has device class 'None', state class 'measurement' unit 'ppm' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-finite value: 'nan'
```

**Comment by pergolafabio** [comment]
I believe, my PH value is too high, and its not reading the current chorine yet...

**Comment by pksoft585** [comment]
Hi, I have maybe similar problem...
After the last update, the chlorine value is still 0. (pH is 6.8). And the ORP value oscillates between 0 and 65. Before the update, it was 10 times higher. The other readings seem fine.
Thank you.

**Comment by jdeath** [comment]
@olivierbarriere can you take a look at this? Seems your changes may have affected something.

**Comment by pergolafabio** [comment]
Also my temperature is now 5 degree warmer :-)

**Comment by olivierbarriere** [comment]
The changes I made were minimal and only impacted the missing chlorine values and battery calculations.
It should not impact the temperature nor ORP. Are the values reported by the integration different from the ones on the device screen?

I updated the cloro again, in order to report "None" instead of "NaN". NaN was working in ESPhome, but it needs to be set to "None" in the integration. Now Home Assistant will now still create the entity with an "unknown" value, instead of "unavailable".

See https://github.com/jdeath/BLE-YC01/pull/8 for more details

**Comment by pergolafabio** [comment]
Thnx for the CH fix, I will test it later by downloading the fix manually or if it will be released...
As for a test, I downgraded back to 0.2 and my temperature is now reporting correctly...

Maybe I'm my case because of the CH error, the integration was crashed and not updating the temp anymore? Maybe I just saw the temp of some hours ago (last state)

**Comment by pergolafabio** [comment]
ok, that works now, its now unknown state
But is it maybe possible to set to "0" instead of unknown? otherwhise the gauge card is not working...

![image](https://github.com/jdeath/BLE-YC01/assets/43251136/733c48e6-bcd0-4ffc-82ac-682df30511ad)

**Comment by pergolafabio** [comment]
i have done this for now ...

```
        if cloro == 65535:
          device.sensors["cloro"] = 0
```

**Comment by olivierbarriere** [comment]
I am using this card: https://github.com/wilsto/pool-monitor-card and it displays NaN when the value is unknown.

**Comment by pergolafabio** [comment]
Thnx for PR
